### ISSUE TITLE
Polling state of tado

### ISSUE THREAD

**Issue by jeyremy** [nitaybz/homebridge-tado-ac#44]
Hi, 
Again thanks for your hard work on this, it's awesome. 

I have two Enchancements in mind : 
1- Refresh state of Thermostat mode or on/off without having to open the home app ( i need this for automation purpose when tado AC starts and stop  )

2- on an other hand, in thermostatic usage the AC is sometime off (when the room is below temperature for example) but appears "on" on homekit. But maybe you don't have that information from tado...

**Comment by nitaybz** [comment]
Hey @jeyremy 

thanks for you feedback...
1. This is something I plan to do but couldn't find the time yet... but this is definitely going to happen... it's a great Idea and it can help shorten the loading time of the home app as well...

2. As for now the plugin doesn't support thermostatic mode, if it works for you that's great, but I never did any adjustments...
I'm planning to do that in the future as a thermostat service instead of the coolerheater that is now.

**Comment by nitaybz** [comment]
Hey @jeyremy  !
Version 3 is finally here with polling state for state and Thermostatic control support.

read the README carefully and update your plugin with:
`sudo npm install -g homebridge-tado-ac`

would love to hear your thoughts

**Comment by jeyremy** [comment]
You are the best ! 

i'm currently testing it. thanks a lot
